# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do

desc "Build and run test"

lane :build_for_testing do |options|
  cocoapods(clean_install: true)
  scan(
    workspace: "MyChat.xcworkspace",
    scheme: "MyChat",
    build_for_testing: true,
    destination: "platform=iOS Simulator,name=iPhone 11,OS=14.4",
    clean: false
    )
  puts "build_for_testing"
end 

lane :run_tests_app do |options|
  run_tests(
    workspace: "MyChat.xcworkspace",
    scheme: "MyChat",
    destination: "platform=iOS Simulator,name=iPhone 11,OS=14.4",
    clean: false
    # test_without_building: true
    )
  puts "run_tests"
end

lane :build_and_test do |options|
  build_for_testing
  # sleep 15
  run_tests_app
end

end