# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane


default_platform(:ios)

platform :ios do

desc "Build and run test"

lane :build_for_testing do |options|
  cocoapods(
    try_repo_update_on_error: true
  )
  scan(
    workspace: "MyChat.xcworkspace",
    scheme: "MyChat",
    build_for_testing: true,
    destination: "platform=iOS Simulator,name=iPhone 11,OS=14.4",
    clean: false
    )
end 

lane :run_tests_app do |options|
  cocoapods(
    try_repo_update_on_error: true
  )
  run_tests(
    workspace: "MyChat.xcworkspace",
    scheme: "MyChat",
    destination: "platform=iOS Simulator,name=iPhone 11,OS=14.4"
    )
end

lane :discord_notifier do |options|

  color = (options[:success] ? 0xd0ec36 : 0x3449df)
  result = (options[:success] ? "Success" : "Fail")

require 'discordrb/webhooks'

webhook_url = ENV["WEBHOOK_URL"].freeze

client = Discordrb::Webhooks::Client.new(url: webhook_url)
client.execute do |builder|
  builder.username = 'SolnyshkinSM'
  builder.content = 'Build result'

  builder.add_embed do |embed|

    embed.title = result
    embed.colour = color
    embed.description = '[Repositories](https://github.com/SolnyshkinSM/MyChat)'
    embed.image = Discordrb::Webhooks::EmbedImage.new(url: 'https://img.ibxk.com.br/2016/06/13/13193755864575.jpg')
    embed.add_field(name: "Platform name", value: ENV["FASTLANE_PLATFORM_NAME"], inline: true)
    embed.timestamp = Time.now
  end
end
end

lane :build_and_test do |options|
  build_for_testing
  run_tests_app
  error do |ex|
    discord_notifier(success: false)
    next
  end  
  discord_notifier(success: true)
end

end